version: "3"

services:
  postgres:
    image: postgres:13
    container_name: db_teste_postgres
    environment:
      POSTGRES_USER: wesleymiranda
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_teste_postgres
    ports:
      - "5434:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
